
on:
  pull_request:
    branches: [dev]
    types:
      - closed
  workflow_dispatch:

jobs:
  IntegrationTest:
    environment: Development
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
        with:
          login_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          keyvault: tdei-secrets
          secrets: |
            QUEUECONNECTION=QUEUECONNECTION
            STORAGECONNECTION=STORAGECONNECTION
            AUTH_HOST=AUTH_HOST
            VALIDATION_SUBSCRIPTION=VALIDATION_SUBSCRIPTION
            VALIDATION_TOPIC=VALIDATION_TOPIC
            DATASVC_TOPIC=DATASVC_TOPIC
      - name: Some step to consume secrets
        run: |
          echo "${{ env.QUEUECONNECTION }} ${{ env.STORAGECONNECTION }}"
  Build:
    environment: Development
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Publish image to Azure Registry
        run: |
          docker build -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }} -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.ref_name == 'main' && 'prod' || github.ref_name }}${{ github.ref_name != 'main' && '-latest' || 'latest' }} .
          docker push ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }} --all-tags
  Deploy:
    needs: Build
    environment: 
      name: Development
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }}